/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 02:19:21 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Appt;
import edu.osu.cs362.CalDay;
import edu.osu.cs362.TimeTable;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeTable_ESTest extends TimeTable_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 44 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 6. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - true
   * Goal 7. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false
   * Goal 8. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 14. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 15. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Positive
   * Goal 16. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 18. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 19. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 20. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 21. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 22. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 139
   * Goal 23. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 140
   * Goal 24. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 25. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 26. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 27. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 28. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 29. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 30. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 31. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 32. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 33. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 34. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 35. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 36. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 37. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 38. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 39. Weak Mutation 76: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable tempAppt -> appt
   * Goal 40. Weak Mutation 77: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable appt -> tempAppt
   * Goal 41. Weak Mutation 78: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceComparisonOperator == -> !=
   * Goal 42. Weak Mutation 79: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp Negation of i
   * Goal 43. Weak Mutation 80: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC 1 i
   * Goal 44. Weak Mutation 81: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      Appt appt0 = new Appt(2, 540, 320, 11, 23, "", (String) null);
      linkedList0.add(appt0);
      Appt appt1 = new Appt(2, 2, 2, 5, 2, "", "xQ");
      linkedList0.offerLast(appt1);
      timeTable0.deleteAppt(linkedList0, appt1);
      assertEquals(1, linkedList0.size());
  }

  //Test case number: 1
  /*
   * 9 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 3. getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;_java.lang.NullPointerException_IMPLICIT
   * Goal 4. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 5. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 6. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 7. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 8. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 9. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      // Undeclared exception!
      try { 
        timeTable0.getApptRange(linkedList0, (GregorianCalendar) null, (GregorianCalendar) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.TimeTable", e);
      }
  }

  //Test case number: 2
  /*
   * 40 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 6. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false
   * Goal 7. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Zero
   * Goal 14. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 15. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 16. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 18. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 19. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 20. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 139
   * Goal 21. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 140
   * Goal 22. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 23. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 24. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 25. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 26. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 27. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 28. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 29. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 30. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 31. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 32. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 33. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 34. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 35. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 36. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 37. Weak Mutation 78: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceComparisonOperator == -> !=
   * Goal 38. Weak Mutation 79: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp Negation of i
   * Goal 39. Weak Mutation 80: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC 1 i
   * Goal 40. Weak Mutation 81: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:139 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      Appt appt0 = new Appt(2, 2, 2, 5, 2, "", "");
      linkedList0.offerLast(appt0);
      timeTable0.deleteAppt(linkedList0, appt0);
      assertEquals(0, linkedList0.size());
  }

  //Test case number: 3
  /*
   * 41 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - true
   * Goal 6. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 7. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - true
   * Goal 8. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 14. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I40 Branch 14 IFEQ L138 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 15. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 16. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 18. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 19. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 20. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 21. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 22. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 144
   * Goal 23. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 24. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 25. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 26. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 27. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 28. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 29. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 30. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 31. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 32. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 33. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 34. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 35. Weak Mutation 71: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> >
   * Goal 36. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 37. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 38. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 39. Weak Mutation 76: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable tempAppt -> appt
   * Goal 40. Weak Mutation 77: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable appt -> tempAppt
   * Goal 41. Weak Mutation 78: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      Appt appt0 = new Appt(2, 540, 320, 11, 23, "", (String) null);
      linkedList0.add(appt0);
      Appt appt1 = new Appt(2, 2, 2, 5, 2, "", "xQ");
      timeTable0.deleteAppt(linkedList0, appt1);
      assertEquals(1, linkedList0.size());
  }

  //Test case number: 4
  /*
   * 33 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true
   * Goal 5. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false
   * Goal 6. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 7. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I27 Branch 13 IF_ICMPGE L136 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;_java.lang.NullPointerException_IMPLICIT
   * Goal 12. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 13. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 14. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 15. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 136
   * Goal 16. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 137
   * Goal 17. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 138
   * Goal 18. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 19. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 20. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 21. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 22. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 23. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   * Goal 24. Weak Mutation 66: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceConstant - 0 -> 1
   * Goal 25. Weak Mutation 67: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp Negation of i
   * Goal 26. Weak Mutation 68: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC 1 i
   * Goal 27. Weak Mutation 69: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - InsertUnaryOp IINC -1 i
   * Goal 28. Weak Mutation 70: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:136 - ReplaceComparisonOperator >= -> -1
   * Goal 29. Weak Mutation 73: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp Negation of i
   * Goal 30. Weak Mutation 74: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC 1 i
   * Goal 31. Weak Mutation 75: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:137 - InsertUnaryOp IINC -1 i
   * Goal 32. Weak Mutation 76: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable tempAppt -> appt
   * Goal 33. Weak Mutation 77: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:138 - ReplaceVariable appt -> tempAppt
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      linkedList0.add((Appt) null);
      // Undeclared exception!
      try { 
        timeTable0.deleteAppt(linkedList0, appt0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.TimeTable", e);
      }
  }

  //Test case number: 5
  /*
   * 20 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true
   * Goal 4. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - false
   * Goal 5. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 6. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 7. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 8. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I14 Branch 12 IFNE L130 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 9. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 10. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 11. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 12. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 130
   * Goal 13. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 131
   * Goal 14. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 15. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 16. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 17. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 18. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 19. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 65: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:130 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      Appt appt0 = new Appt((-1), (-1), (-1), 0, 0, "", "/");
      LinkedList<Appt> linkedList1 = timeTable0.deleteAppt(linkedList0, appt0);
      assertNull(linkedList1);
  }

  //Test case number: 6
  /*
   * 16 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false
   * Goal 3. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - false
   * Goal 4. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 5. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I5 Branch 11 IFNONNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 6. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - false in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 7. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 8. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 9. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 10. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 128
   * Goal 11. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 12. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 14. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 15. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   * Goal 16. Weak Mutation 64: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(59, 59, (-330), (-330), 577, 577);
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.appts;
      LinkedList<Appt> linkedList1 = timeTable0.deleteAppt(linkedList0, (Appt) null);
      assertNull(linkedList1);
  }

  //Test case number: 7
  /*
   * 13 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - true
   * Goal 3. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 4. Branch edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: I3 Branch 10 IFNULL L127 - true in context: edu.osu.cs362.TimeTable:deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 5. [Output]: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:Null
   * Goal 6. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 7. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 127
   * Goal 8. edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;: Line 128
   * Goal 9. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 10. [METHOD] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 11. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 12. [METHODNOEX] edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;
   * Goal 13. Weak Mutation 63: edu.osu.cs362.TimeTable.deleteAppt(Ljava/util/LinkedList;Ledu/osu/cs362/Appt;)Ljava/util/LinkedList;:127 - ReplaceComparisonOperator = null -> != null
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      Appt appt0 = new Appt((-1), (-1), (-1), 0, 0, "", "/");
      LinkedList<Appt> linkedList0 = timeTable0.deleteAppt((LinkedList<Appt>) null, appt0);
      assertNull(linkedList0);
  }

  //Test case number: 8
  /*
   * 64 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true
   * Goal 3. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - true
   * Goal 4. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false
   * Goal 5. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - true
   * Goal 6. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - false
   * Goal 7. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I82 Branch 4 IFNE L59 - false
   * Goal 8. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 9. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 10. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 11. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 12. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 13. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I70 Branch 3 IF_ICMPGE L57 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 14. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I82 Branch 4 IFNE L59 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 15. [Output]: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:NonNull:java.util.LinkedList:size()I:Positive
   * Goal 16. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 17. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 18. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 19. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 50
   * Goal 20. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 51
   * Goal 21. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 52
   * Goal 22. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 53
   * Goal 23. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 57
   * Goal 24. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 58
   * Goal 25. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 59
   * Goal 26. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 84
   * Goal 27. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 28. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 29. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 30. [METHODNOEX] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 31. Weak Mutation 0: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable firstDay -> lastDay
   * Goal 32. Weak Mutation 1: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable lastDay -> firstDay
   * Goal 33. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 34. Weak Mutation 5: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:50 - ReplaceVariable firstDay -> lastDay
   * Goal 35. Weak Mutation 6: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> firstDay
   * Goal 36. Weak Mutation 7: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> lastDay
   * Goal 37. Weak Mutation 8: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> firstDay
   * Goal 38. Weak Mutation 9: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> nextDay
   * Goal 39. Weak Mutation 10: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceComparisonOperator == -> !=
   * Goal 40. Weak Mutation 11: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable calDays -> appts
   * Goal 41. Weak Mutation 12: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> firstDay
   * Goal 42. Weak Mutation 13: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> lastDay
   * Goal 43. Weak Mutation 14: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 44. Weak Mutation 15: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 45. Weak Mutation 16: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 46. Weak Mutation 17: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 47. Weak Mutation 18: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 0
   * Goal 48. Weak Mutation 19: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 1
   * Goal 49. Weak Mutation 20: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> -1
   * Goal 50. Weak Mutation 21: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 4
   * Goal 51. Weak Mutation 22: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 6
   * Goal 52. Weak Mutation 23: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 1 -> 0
   * Goal 53. Weak Mutation 24: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceConstant - 0 -> 1
   * Goal 54. Weak Mutation 25: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp Negation of i
   * Goal 55. Weak Mutation 26: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp IINC 1 i
   * Goal 56. Weak Mutation 27: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - InsertUnaryOp IINC -1 i
   * Goal 57. Weak Mutation 28: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceVariable appts -> calDays
   * Goal 58. Weak Mutation 29: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceComparisonOperator >= -> -1
   * Goal 59. Weak Mutation 30: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:57 - ReplaceComparisonOperator >= -> >
   * Goal 60. Weak Mutation 32: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - ReplaceVariable appts -> calDays
   * Goal 61. Weak Mutation 33: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp Negation of i
   * Goal 62. Weak Mutation 34: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp IINC 1 i
   * Goal 63. Weak Mutation 35: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:58 - InsertUnaryOp IINC -1 i
   * Goal 64. Weak Mutation 36: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:59 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(0, 0, 0);
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      mockGregorianCalendar0.clear();
      LinkedList<Appt> linkedList0 = calDay0.getAppts();
      MockGregorianCalendar mockGregorianCalendar1 = new MockGregorianCalendar(1, (-3239), 1, 589, 1491, (-3239));
      Appt appt0 = new Appt(1312, 2936, (-2909), 1, 589, (String) null, (String) null);
      linkedList0.add(appt0);
      timeTable0.getApptRange(linkedList0, mockGregorianCalendar0, mockGregorianCalendar1);
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=1,MONTH=-3239,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=589,HOUR_OF_DAY=589,MINUTE=1491,SECOND=-3239,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar1.toString());
  }

  //Test case number: 9
  /*
   * 15 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - false
   * Goal 3. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 4. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 5. getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 6. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 7. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 8. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 9. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 44
   * Goal 10. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 11. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 12. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 13. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 14. Weak Mutation 3: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:44 - ReplaceConstant - Second date specified is not before the first date specified. -> 
   * Goal 15. Weak Mutation 4: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:44 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      LinkedList<Appt> linkedList0 = new LinkedList<Appt>();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      // Undeclared exception!
      try { 
        timeTable0.getApptRange(linkedList0, mockGregorianCalendar0, mockGregorianCalendar0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Second date specified is not before the first date specified.
         //
         assertThrownBy("edu.osu.cs362.TimeTable", e);
      }
  }

  //Test case number: 10
  /*
   * 39 covered goals:
   * Goal 1. edu.osu.cs362.TimeTable.<init>()V: root-Branch
   * Goal 2. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true
   * Goal 3. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false
   * Goal 4. Branch edu.osu.cs362.TimeTable.<init>()V: root-Branch in context: edu.osu.cs362.TimeTable:<init>()V
   * Goal 5. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I11 Branch 1 IFNE L43 - true in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 6. Branch edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: I43 Branch 2 IFEQ L51 - false in context: edu.osu.cs362.TimeTable:getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 7. getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 8. edu.osu.cs362.TimeTable.<init>()V: Line 27
   * Goal 9. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 40
   * Goal 10. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 43
   * Goal 11. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 50
   * Goal 12. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 51
   * Goal 13. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 52
   * Goal 14. edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;: Line 53
   * Goal 15. [METHOD] edu.osu.cs362.TimeTable.<init>()V
   * Goal 16. [METHOD] edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;
   * Goal 17. [METHODNOEX] edu.osu.cs362.TimeTable.<init>()V
   * Goal 18. Weak Mutation 0: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable firstDay -> lastDay
   * Goal 19. Weak Mutation 1: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceVariable lastDay -> firstDay
   * Goal 20. Weak Mutation 2: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:43 - ReplaceComparisonOperator != -> ==
   * Goal 21. Weak Mutation 5: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:50 - ReplaceVariable firstDay -> lastDay
   * Goal 22. Weak Mutation 6: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> firstDay
   * Goal 23. Weak Mutation 7: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable nextDay -> lastDay
   * Goal 24. Weak Mutation 8: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> firstDay
   * Goal 25. Weak Mutation 9: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceVariable lastDay -> nextDay
   * Goal 26. Weak Mutation 10: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:51 - ReplaceComparisonOperator == -> !=
   * Goal 27. Weak Mutation 11: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable calDays -> appts
   * Goal 28. Weak Mutation 12: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> firstDay
   * Goal 29. Weak Mutation 13: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:52 - ReplaceVariable nextDay -> lastDay
   * Goal 30. Weak Mutation 14: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 31. Weak Mutation 15: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 32. Weak Mutation 16: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> firstDay
   * Goal 33. Weak Mutation 17: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceVariable nextDay -> lastDay
   * Goal 34. Weak Mutation 18: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 0
   * Goal 35. Weak Mutation 19: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 1
   * Goal 36. Weak Mutation 20: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> -1
   * Goal 37. Weak Mutation 21: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 4
   * Goal 38. Weak Mutation 22: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 5 -> 6
   * Goal 39. Weak Mutation 23: edu.osu.cs362.TimeTable.getApptRange(Ljava/util/LinkedList;Ljava/util/GregorianCalendar;Ljava/util/GregorianCalendar;)Ljava/util/LinkedList;:53 - ReplaceConstant - 1 -> 0
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TimeTable timeTable0 = new TimeTable();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(0, 0, 0);
      CalDay calDay0 = new CalDay((GregorianCalendar) mockGregorianCalendar0);
      LinkedList<Appt> linkedList0 = calDay0.getAppts();
      MockGregorianCalendar mockGregorianCalendar1 = new MockGregorianCalendar(1, (-3239), 1, 589, 1491, (-3239));
      // Undeclared exception!
      try { 
        timeTable0.getApptRange(linkedList0, mockGregorianCalendar0, mockGregorianCalendar1);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }
}
